name: Linting

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  run-pylint:
    name: Run Python Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: 'pip'

      - name: Install Linters
        run: pip install flake8

      - name: Run flake8
        run: flake8 .
